kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
nodes:
  # Master * 3
  - role: control-plane
    image: kindest/node:v1.18.2
  - role: control-plane
    image: kindest/node:v1.18.2
  - role: control-plane
    image: kindest/node:v1.18.2
  # Worker * 3
  - role: worker
    image: kindest/node:v1.18.2
  - role: worker
    image: kindest/node:v1.18.2
  - role: worker
    image: kindest/node:v1.18.2
    