kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: practice-cluster
nodes:
  # Master * 1
  - role: control-plane
    image: kindest/node:v1.21.1
  # Worker * 3
  - role: worker
    image: kindest/node:v1.21.1
  - role: worker
    image: kindest/node:v1.21.1
  - role: worker
    image: kindest/node:v1.21.1
